package com.example.footballmadrid.models;

import jakarta.persistence.*;

import java.util.LinkedList;
import java.util.List;

@Entity
@Table(name = "userModel")
public class UserModel {
    @Id
    private Long id;
//non relational variables

    private String username;
    private String password;



    //relational variables
    //List of Games
    @ManyToMany(fetch = FetchType.EAGER)
    @JoinTable(
            name = "game_user",
            joinColumns = {@JoinColumn(name = "user_id")},
            inverseJoinColumns = {@JoinColumn(name = "game_id")}
    )
    private List<GameModel> gameModel = new LinkedList<>();




    //constructors

    public UserModel() {
    }
    public UserModel(String username, String password) {
        this.username = username;
        this.password = password;
    }
    public UserModel(Long id,String username, String password) {
        this.username = username;
        this.password = password;
        this.id = id;
    }





    //getters and setters, autogenerated

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getUsername() {
        return username;
    }


    public void setUsername(String username) {
        this.username = username;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public List<GameModel> getGameModel() {
        return gameModel;
    }

    public void setGameModel(List<GameModel> gameModel) {
        this.gameModel = gameModel;
    }
}
